# Configuración del analizador estático de Dart.
# Define las reglas de linter para asegurar calidad y consistencia en el código.

# Incluye el conjunto de reglas recomendadas por el equipo de Flutter.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Reglas personalizadas pueden agregarse aquí.
    # Por ejemplo, para forzar comillas simples:
    # prefer_single_quotes: true
