name: admin_web
description: "Panel de administración web para VecinApp."
# Evita publicación accidental en pub.dev
publish_to: 'none' 

# Versionamiento semántico: Major.Minor.Patch + Build Number
version: 1.0.0+1

environment:
  # Versión de Dart compatible con Flutter 3.10+
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Estilos ---
  # Iconos estilo iOS
  cupertino_icons: ^1.0.8
  # Fuentes de Google
  # Fuentes de Google
  google_fonts: ^6.1.0
  quickalert: ^1.0.2  # Alertas bonitas
  flutter_map: ^6.1.0 # Mapas (OpenStreetMap)
  latlong2: ^0.9.0    # Coordenadas para mapas
  intl: ^0.19.0       # Formato de fechas
  file_picker: ^6.1.1 # Selección de archivos
  excel: ^4.0.0       # Lectura de Excel

  # --- Backend & Conectividad ---
  # Autenticación con Firebase
  firebase_auth: ^4.17.8
  # Core de Firebase
  firebase_core: ^2.27.0
  # Peticiones HTTP
  http: ^1.2.0
  # Gestión de estado
  provider: ^6.1.2
  # Manejo de variables de entorno (.env)
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de linter recomendadas para Flutter
  flutter_lints: ^3.0.0

flutter:
  # Habilita iconos Material Design
  uses-material-design: true

  # --- Assets ---
  # Incluimos el archivo .env para configuración
  assets:
    - assets/images/
    - .env
